"""Generate the Webots worlds from lot.py, scenario.py (seed 0) and rig.py.

  worlds/parking_row.wbt   the parking lot (asphalt)
  worlds/calibration.wbt   same, but a high-contrast checkerboard floor, used to compute the
                           camera body masks (autopark calibrate_masks)

Run after changing lot geometry, cameras or assets (in src/autopark/autopark_sim):
    python3 -m autopark_sim.generate_world worlds
Unit tests check that the committed worlds match this generator.
"""
import sys

from autopark_sim.lot import painted_lines
from autopark_sim.rig import CAMERAS
from autopark_sim.scenario import CAR_MODELS, EGO_Z, make_scenario

R2025A = 'https://raw.githubusercontent.com/cyberbotics/webots/R2025a/projects'
PROTOS = {
    'TexturedBackground': 'objects/backgrounds/protos/TexturedBackground.proto',
    'TexturedBackgroundLight': 'objects/backgrounds/protos/TexturedBackgroundLight.proto',
    'Floor': 'objects/floors/protos/Floor.proto',
    'Asphalt': 'appearances/protos/Asphalt.proto',
    'ToyotaPrius': 'vehicles/protos/toyota/ToyotaPrius.proto',
}
CAR_PROTO_PATHS = {
    'TeslaModel3Simple': 'vehicles/protos/tesla/TeslaModel3Simple.proto',
    'BmwX5Simple': 'vehicles/protos/bmw/BmwX5Simple.proto',
    'CitroenCZeroSimple': 'vehicles/protos/citroen/CitroenCZeroSimple.proto',
    'LincolnMKZSimple': 'vehicles/protos/lincoln/LincolnMKZSimple.proto',
    'RangeRoverSportSVRSimple': 'vehicles/protos/range_rover/RangeRoverSportSVRSimple.proto',
    'ToyotaPriusSimple': 'vehicles/protos/toyota/ToyotaPriusSimple.proto',
}


def _cameras():
    """Cameras from rig.py, all mounted in sensorsSlotCenter (origin = base_link), plus IMU."""
    cams = '\n'.join(
        f"""    Pose {{
      translation {c.x} {c.y} {c.z}
      rotation 0 0 1 {c.yaw:.6f}
      children [ Camera {{ name "cam_{c.name}" rotation 0 1 0 {c.pitch} width {c.width} height {c.height} fieldOfView {c.hfov} projection \"{c.projection}\" near 0.05 far 60 }} ]
    }}""" for c in CAMERAS)
    return f"""  sensorsSlotCenter [
{cams}
    Gyro {{ name "gyro" }}
    Accelerometer {{ name "accelerometer" }}
  ]"""


def world_string(calibration=False):
    sc = make_scenario(0)
    ex, ey, eyaw = sc.ego
    lines = '\n'.join(
        f'    Pose {{ translation {x:.3f} {y:.3f} 0.005 children [ Shape {{ '
        f'appearance USE PAINT geometry Box {{ size {sx:.3f} {sy:.3f} 0.01 }} }} ] }}'
        for x, y, sx, sy in painted_lines())
    # The first line defines the PAINT appearance.
    lines = lines.replace('appearance USE PAINT', 'appearance DEF PAINT PBRAppearance '
                          '{ baseColor 0.95 0.95 0.92 roughness 0.9 metalness 0 }', 1)
    externs = '\n'.join(f'EXTERNPROTO "{R2025A}/{p}"' for p in PROTOS.values())
    importable = '\n'.join(f'IMPORTABLE EXTERNPROTO "{R2025A}/{CAR_PROTO_PATHS[m]}"'
                           for m in sorted(CAR_MODELS))
    parked = '\n'.join(c.webots_string() for c in sc.parked)
    if calibration:  # Floor's default appearance is a chequered Parquetry
        floor = 'Floor {\n  size 100 100\n  tileSize 1 1\n}'
    else:
        floor = 'Floor {\n  size 100 100\n  tileSize 4 4\n  appearance Asphalt { }\n}'
    return f"""#VRML_SIM R2025a utf8
# GENERATED by autopark_sim/generate_world.py -- do not edit by hand.
# Parking row world: 2 x 8 perpendicular slots across a 7 m aisle (see lot.py).
# Parked cars below are scenario seed 0; the gt_supervisor re-spawns them from its seed.

{externs}
{importable}

WorldInfo {{
  info [ "autopark: vision-based perpendicular parking" ]
  basicTimeStep 20
}}
Viewpoint {{
  orientation -0.3323 0.3323 0.8827 1.6952
  position 0 -26 22
}}
TexturedBackground {{
  texture "noon_cloudy_countryside"
}}
TexturedBackgroundLight {{
  texture "noon_cloudy_countryside"
  castShadows FALSE
}}
{floor}
DEF LINES Solid {{
  name "painted lines"
  children [
{lines}
  ]
}}
DEF GT_SUPERVISOR Robot {{
  name "gt_supervisor"
  controller "<extern>"
  supervisor TRUE
  children [
    DEF DEMO_CAM Pose {{
      translation 0 0 -20
      children [ Camera {{ name "demo_cam" width 1280 height 720 fieldOfView 0.9 near 0.1 far 100 }} ]
    }}
  ]
}}
DEF EGO ToyotaPrius {{
  translation {ex:.4f} {ey:.4f} {EGO_Z}
  rotation 0 0 1 {eyaw:.5f}
  name "ego_car"
  controller "<extern>"
  color 0.9 0.45 0.0
{_cameras()}
}}
{parked}
"""


WORLDS = {'parking_row.wbt': False, 'calibration.wbt': True}


def main():
    import os
    out_dir = sys.argv[1] if len(sys.argv) > 1 else '.'
    for name, calibration in WORLDS.items():
        path = os.path.join(out_dir, name)
        with open(path, 'w') as f:
            f.write(world_string(calibration))
        print(f'wrote {path}')


if __name__ == '__main__':
    main()
