"""Generate worlds/parking_row.wbt from lot.py + scenario.py (seed 0).

Run after changing lot geometry, cameras or assets:
    python3 -m autopark_sim.generate_world src/autopark/autopark_sim/worlds/parking_row.wbt
A unit test checks that the committed world matches this generator.
"""
import sys

from autopark_sim.lot import painted_lines
from autopark_sim.scenario import CAR_MODELS, EGO_Z, make_scenario

R2025A = 'https://raw.githubusercontent.com/cyberbotics/webots/R2025a/projects'
PROTOS = {
    'TexturedBackground': 'objects/backgrounds/protos/TexturedBackground.proto',
    'TexturedBackgroundLight': 'objects/backgrounds/protos/TexturedBackgroundLight.proto',
    'Floor': 'objects/floors/protos/Floor.proto',
    'Asphalt': 'appearances/protos/Asphalt.proto',
    'ToyotaPrius': 'vehicles/protos/toyota/ToyotaPrius.proto',
}
CAR_PROTO_PATHS = {
    'TeslaModel3Simple': 'vehicles/protos/tesla/TeslaModel3Simple.proto',
    'BmwX5Simple': 'vehicles/protos/bmw/BmwX5Simple.proto',
    'CitroenCZeroSimple': 'vehicles/protos/citroen/CitroenCZeroSimple.proto',
    'LincolnMKZSimple': 'vehicles/protos/lincoln/LincolnMKZSimple.proto',
    'RangeRoverSportSVRSimple': 'vehicles/protos/range_rover/RangeRoverSportSVRSimple.proto',
    'ToyotaPriusSimple': 'vehicles/protos/toyota/ToyotaPriusSimple.proto',
}

# Cameras: 320x240, 2.0 rad HFOV, pitched down for ground coverage (tuned in milestone 2).
CAM = 'width 320 height 240 fieldOfView 2.0 near 0.05 far 60'


def _cameras():
    return f"""  sensorsSlotFront [
    Camera {{ name "cam_front" translation 0.05 0 0.25 rotation 0 1 0 0.45 {CAM} }}
  ]
  sensorsSlotRear [
    Camera {{ name "cam_rear" translation 0.05 0 0.35 rotation 0 1 0 0.45 {CAM} }}
  ]
  sensorsSlotCenter [
    Pose {{
      translation 1.9 0.95 0.75
      rotation 0 0 1 1.5708
      children [ Camera {{ name "cam_left" rotation 0 1 0 0.75 {CAM} }} ]
    }}
    Pose {{
      translation 1.9 -0.95 0.75
      rotation 0 0 1 -1.5708
      children [ Camera {{ name "cam_right" rotation 0 1 0 0.75 {CAM} }} ]
    }}
    Gyro {{ name "gyro" }}
    Accelerometer {{ name "accelerometer" }}
  ]"""


def world_string():
    sc = make_scenario(0)
    ex, ey, eyaw = sc.ego
    lines = '\n'.join(
        f'    Pose {{ translation {x:.3f} {y:.3f} 0.005 children [ Shape {{ '
        f'appearance USE PAINT geometry Box {{ size {sx:.3f} {sy:.3f} 0.01 }} }} ] }}'
        for x, y, sx, sy in painted_lines())
    # The first line defines the PAINT appearance.
    lines = lines.replace('appearance USE PAINT', 'appearance DEF PAINT PBRAppearance '
                          '{ baseColor 0.95 0.95 0.92 roughness 0.9 metalness 0 }', 1)
    externs = '\n'.join(f'EXTERNPROTO "{R2025A}/{p}"' for p in PROTOS.values())
    importable = '\n'.join(f'IMPORTABLE EXTERNPROTO "{R2025A}/{CAR_PROTO_PATHS[m]}"'
                           for m in sorted(CAR_MODELS))
    parked = '\n'.join(c.webots_string() for c in sc.parked)
    return f"""#VRML_SIM R2025a utf8
# GENERATED by autopark_sim/generate_world.py -- do not edit by hand.
# Parking row world: 2 x 8 perpendicular slots across a 7 m aisle (see lot.py).
# Parked cars below are scenario seed 0; the gt_supervisor re-spawns them from its seed.

{externs}
{importable}

WorldInfo {{
  info [ "autopark: vision-based perpendicular parking" ]
  basicTimeStep 20
}}
Viewpoint {{
  orientation -0.3323 0.3323 0.8827 1.6952
  position 0 -26 22
}}
TexturedBackground {{
  texture "noon_cloudy_countryside"
}}
TexturedBackgroundLight {{
  texture "noon_cloudy_countryside"
  castShadows FALSE
}}
Floor {{
  size 100 100
  tileSize 4 4
  appearance Asphalt {{ }}
}}
DEF LINES Solid {{
  name "painted lines"
  children [
{lines}
  ]
}}
DEF GT_SUPERVISOR Robot {{
  name "gt_supervisor"
  controller "<extern>"
  supervisor TRUE
}}
DEF EGO ToyotaPrius {{
  translation {ex:.4f} {ey:.4f} {EGO_Z}
  rotation 0 0 1 {eyaw:.5f}
  name "ego_car"
  controller "<extern>"
  color 0.9 0.45 0.0
{_cameras()}
}}
{parked}
"""


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else 'parking_row.wbt'
    with open(out, 'w') as f:
        f.write(world_string())
    print(f'wrote {out}')


if __name__ == '__main__':
    main()
